### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by project707** [wardrobecms/core-archived#108]
I would love to use Wardrobe CMS in production, but it seems like there are a lot of issues that have gone unclosed or solved for a very long time and there are issues with the documentation.

Is it possible many are solved and just not closed?

**Comment by tomsonar** [comment]
Can't be. There's too many issues. I'm surprised if anyone can even use it still. I now can't run a Composer update. It's stuck on dependencies somewhere. Something is obviously not being maintained.

**Comment by Jeroen-G** [comment]
You probably want to check the author's blog about Wardrobe: http://ericlbarnes.com/category/wardrobe/

**Comment by tomsonar** [comment]
Ah, cool. Thanks.
