### ISSUE TITLE
Install for Laravel 4.2

### ISSUE THREAD

**Issue by marktopper** [wardrobecms/core-archived#109]
When I try to add `"wardrobe/core": "1.0.*"` to composer and run `composer update`.

I get the following result on Laravel 4.2:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wardrobe/core v1.0.1 requires laravel/framework 4.0.x -> no matching package found.
    - wardrobe/core v1.0.0 requires laravel/framework 4.0.x -> no matching package found.
    - Installation request for wardrobe/core 1.0.* -> satisfiable by wardrobe/core[v1.0.0, v1.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Any packages I can add for Laravel 4.2?

**Comment by project707** [comment]
You can sort of get it to install initially by specifying a different version number for Wardrobe in composer.json - everything here including the documentation is out of date. However, even doing that I was unable to _fully_ install this for 4.2. I think I used 1.2.\* or dev-master to get that far.

Anyhow, no matter what i did I was required to install the "Laravel Package Installer" (which seems like a bad idea to require IMO) even if following the composer-only instruction, but then that also seems to not work as it didn't register the package commands' required namespace, so I was never able to really get it running.

**Comment by ericlbarnes** [comment]
If you want Laravel 4.2 checkout the develop branch here - 
https://github.com/wardrobecms/wardrobe/tree/develop

Docs haven't been updated for it but it should at least get you up and running. I'm also rebuilding Wardrobe for Laravel 5 and have been documenting the process on my personal site - http://ericlbarnes.com/category/wardrobe/

**Comment by project707** [comment]
@ericbarnes thanks for the update. How stable would you say the develop branch is currently?

And you mean the develop branch here right? 
https://github.com/wardrobecms/core/tree/develop

We're trying to install core specifically. I really think the most valuable thing wardrobe has is the ability to be added to an existing Laravel application. This is a very common use case from what I've seen.

**Comment by marktopper** [comment]
@ericbarnes, thanks.

I will give it a try and let you all know if it's unstable.

**Comment by ericlbarnes** [comment]
In develop branch core was renamed to cabinet - https://github.com/wardrobecms/cabinet

It is pretty stable. I ran it in production for 6 months or more this year.

**Comment by project707** [comment]
@ericbarnes I tried installing it with no success. The Laravel package installer doesn't work for me. It's command namespace is never available when following the install directions. It also doesn't look to be maintained, or maybe it's documentation has not been updated?
