### ISSUE TITLE
Wardrobe::posts() does not work properly

### ISSUE THREAD

**Issue by Chumper** [wardrobecms/core-archived#17]
When i am on the index page like `http://localhost/?page=1`or `loaclhost`, i get all posts with Wardrobe::posts().

But if i am on page 2, like `http://localhost/?page=2` i won't get any posts back.

I looked into the code and you call active with (in my case) `1` post per page, shouldn't it call `all()` on the repository?

**Comment by rtablada** [comment]
The default for Wardrobe::posts() is to give the paginated results. I'm not sure what you are asking about it calling `all()`.

There was a configuration failure that was fixed by 9855574 where I had missed a configuration migration to the package syntax. But the null argument should have been caught by the paginate method in the postRepository.

**Comment by rtablada** [comment]
Also, are you using core within a Laravel Project, Wardrobe/Wardrobe etc. so we can look at your env.

**Comment by Chumper** [comment]
Now it works like you suggested ;)
I am using the wadrobe skeleton with a custom theme.
In my theme i want to display all posts titles in a sidebar, now i have to call `Wardrobe::posts(array('per_page' => largenumber))` to get my wished result.

I want to have a command to get all posts on every page, ignoring the pagination.

**Comment by rtablada** [comment]
Ok, will have to talk to @ericbarnes on that one. He's making more of the feature decisions so I don't want to hack out opinions.

Maybe a getRepo function on the facade that gives you some power to directly interact on the repo?

**Comment by Chumper** [comment]
That would be great, because atm i can't access all post titles, even on page 2, because of the pagination.

**Comment by ericlbarnes** [comment]
I personally think if per_page isn't set then the facade just sets it to a fairly high number like 50 or something. 

—
Eric Barnes

**Comment by Chumper** [comment]
The problem is the following: i have two posts and set per_page in the config to 1.
On page two with per_page 50 i won't get anymore post, because it will skip the first 50 results on page 2

**Comment by rtablada** [comment]
I think a getPostRepo would be nice similar to the way that the getAuth method allows you to tap into the auth provider.
