### ISSUE TITLE
[Proposal] Auto-save

### ISSUE THREAD

**Issue by rtablada** [wardrobecms/core-archived#2]
I am thinking that the current working document for a user could be stored in cache under the key `wardrobe::username-curent`.

In reality we could just dump the input as a raw Input array? Then have a query

```
if CachedPost
   populateWithCachedPost
else
   populateWithNull
```

@ericbarnes what are you thinking from the JS side. You tell me what you want the data to look like and I will try my darndest to make it happen

**Comment by ericlbarnes** [comment]
I think I have a better simpler idea. Give me a few days to experiment and see if it's doable.

**Comment by ericlbarnes** [comment]
I tweeted this but figured it would be good to include it here in case you have any thoughts: 
http://screencast.com/t/1UARkePzQ

I will push this up after I clean it up more. Basically it utilizes local storage and a simple pub/sub to keep the preview up to date.  All this requires is adding a new preview template with 7 lines of js.

**Comment by rtablada** [comment]
Sounds cool. Don't have wifi to watch it.
