### ISSUE TITLE
/wardrobe/login hardcoded instead of using admin prefix

### ISSUE THREAD

**Issue by Jakobud** [wardrobecms/core-archived#24]
Look here:  https://github.com/wardrobecms/core/blob/master/src/Wardrobe/Core/Controllers/LoginController.php#L63

It hardcodes the route as `wardrobe/login` instead of calling on the prefix value set in `/app/config/packages/wardrobe/core/routes.php`.  I changed my prefix from `wardrobe` to `admin` and that is how I came across this bug.

I thought maybe I could just change it to

`...(Config::get('core::routes.admin_group_rules') . '/login');`

But that doesn't work I guess since you are trying to call a config value from within the package source.  I'm not sure how to fix this to make it dynamically use the prefix value.

**Comment by rtablada** [comment]
![http://24.media.tumblr.com/4c1681b2fa329b340b88366860ab367e/tumblr_mph9qquSYL1s1fsigo1_250.gif](I did it!)
