### ISSUE TITLE
Make theme view files non-public?

### ISSUE THREAD

**Issue by Jakobud** [wardrobecms/core-archived#25]
Why are the theme view files in the public folder?  Is it not possible to keep them in the app/view folder?  Just wondering for security reasons for the rare case where your view files may have sensitive information or Blade comments in them.

**Comment by rtablada** [comment]
They are together to help keep together assets and views. It also helps publishing assets quickly. You can move them into views if you like.

**Comment by ericlbarnes** [comment]
Yes what @rtablada said is correct. I wanted them in public so people releasing themes could have simple instructions such as "move this folder to public/themes/" and then activate it.

**Comment by Jakobud** [comment]
Okay I will try that out.  Thanks guys!
