### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by tshafer** [wardrobecms/core-archived#28]
I get the error when trying to install the core.

http://paste.laravel.com/Mxg

**Comment by Garbee** [comment]
I am unable to reproduce this on a fresh install. Is it still any issue for anyone else?

**Comment by ericlbarnes** [comment]
Maybe composer was having issues when @tshafer was installing? I haven't seen this before either.

**Comment by Garbee** [comment]
I just tested installing base laravel and adding wardrobe-core to the composer and installing, so it is working fine as of now.

**Comment by ericlbarnes** [comment]
Thanks for the follow up. I'm going to close this but if you still have an issue @tshafer just let us know.
