### ISSUE TITLE
Image dragging not working on localhost

### ISSUE THREAD

**Issue by seblavoie** [wardrobecms/core-archived#30]
There seems to be a problem with image drag and drop when running on localhost. The image get copied in the folder but the markdown isn't generated. Although it works in production. I'm not sure what could cause this or if this only happens to me but I wanted to point it out.

**Comment by ericlbarnes** [comment]
What browser are you running? Also can you open console and see if any errors are reported. 

```
—
```

Eric Barnes

**Comment by seblavoie** [comment]
I am on Google Chrome v.29 and tested on Safari 6.0.5, same problem. But I don't think it's about the browser since it works when it's online. Also the console isn't telling anything. I am running on localhost:8000 from a basic `php artisan serve` if that can help.

**Comment by ericlbarnes** [comment]
I just tried this with php artisan serve and didn't have any issues. Can you try turning on the "pause on exceptions" in chrome? It's a little button in the sources panel: 
https://developers.google.com/chrome-developer-tools/docs/javascript-debugging#pause-on-exceptions

This actually has me stumped. So if you have any thoughts please pass it along :smile:

**Comment by seblavoie** [comment]
I have no idea what happened but when I retried it today, it just worked. I guess I should have restarted before filing this bug. Sorry about that :P
