### ISSUE TITLE
wardrobe:cofig vs wardrobe:config

### ISSUE THREAD

**Issue by matalina** [wardrobecms/core-archived#39]
In the documentation it's `wardrobe:config` when you actually have to run `wardrobe:cofig`

**Comment by rtablada** [comment]
This should have been fixed a bit ago.

**Comment by matalina** [comment]
I just pulled from core about 20 mins ago

**Comment by rtablada** [comment]
What version are you requiring?

**Comment by matalina** [comment]
The one packagist says to:  "wardrobe/core": "dev-develop"

**Comment by rtablada** [comment]
I know that it has been fixed on dev-master I'm not sure if Eric has rebased the develop branch.

**Comment by matalina** [comment]
okay.

**Comment by ericlbarnes** [comment]
Develop should be up to date now. Sorry about that.

**Comment by ghost** [comment]
still not working :(

**Comment by ericlbarnes** [comment]
Just pushed v1.0.1 which should hopefully fix this now. Let me know if that isn't the case.
