### ISSUE TITLE
Integration with existing site

### ISSUE THREAD

**Issue by Jakobud** [wardrobecms/core-archived#40]
All the Wardrobe examples I've seen have Wardrobe installed into it's own standalone Laravel installation.  Can Wardrobe be easily installed into an existing Laravel installation that already has hundreds of routes and controllers, etc?  Is it flexible for this?  Or best at leaving standalone?

**Comment by rtablada** [comment]
I have core installed in an existing laravel application with no problems.

**Comment by rtablada** [comment]
Stuff like this is also best for the forums at http://wardrobecms.com/forum/

**Comment by Jakobud** [comment]
Ah thanks for the forum link.  Had no idea where else to ask the question.  Thanks
