### ISSUE TITLE
Error with wardrobe.per_page

### ISSUE THREAD

**Issue by adamgoose** [wardrobecms/core-archived#55]
Haven't researched where else this issue occurs, but in PostController::index(), the Config::get() method is not properly retrieving the per_page configuration.

**Comment by ericlbarnes** [comment]
Did you run `php artisan config:publish wardrobe/core`? 

The wardrobe config file should be in app/config/packages/wardrobe/core/ directory.

**Comment by adamgoose** [comment]
Yes, I did. The file was there, and the configuration value was appropriately set.

**Comment by ericlbarnes** [comment]
@adamgoose Was you able to get this sorted?

**Comment by adamgoose** [comment]
Yes, by not using any functions that utilize this feature. I used the new facadeSearch method instead.
