### ISSUE TITLE
When trying to artisan wardrobe:config errors are produced

### ISSUE THREAD

**Issue by tpavlek** [wardrobecms/core-archived#56]
Trying to install wardrobe in an existing laravel application I get this error:

{"error":{"type":"ErrorException","message":"Argument 2 passed to Illuminate\Auth\Guard::__construct() must be an instance of Illuminate\Session\Store, instance of Illuminate\Session\SessionManager given, called in \/home\/ebon\/uacs\/vendor\/wardrobe\/core\/src\/Wardrobe\/Core\/Facades\/Wardrobe.php on line 62 and defined","file":"\/home\/ebon\/uacs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php","line":76}}

(where /home/ebon/uacs is the directory the laravel application is hosted in)

**Comment by ericlbarnes** [comment]
You may have to change composer to use `"wardrobe/core": "dev-master"` if you aren't already.
