### ISSUE TITLE
Is there an easy way to disable internal wardrobe auth?

### ISSUE THREAD

**Issue by tpavlek** [wardrobecms/core-archived#57]
I've taken a brief look at some of the wardrobe source, but cannot see an easy way to disable internal wardrobe authentication. My application already has a sufficient authentication system, and I'd prefer to use that.

**Comment by ericlbarnes** [comment]
You should probably ask this in the forums: http://wardrobecms.com/forum

I think some people have indeed done this but I personally haven't.
