### ISSUE TITLE
how would I overwrite changes to wardrobe core?

### ISSUE THREAD

**Issue by newtonianb** [wardrobecms/core-archived#58]
I have a couple things I need to change to properly integrate this, namely the table names used in the models and a couple other things across models/views/controllers. Where would I make these changes? If I make it directly in the vendor directory it will get overwritten when I do a composer update.

What makes most sense to me would be to clone the repo and make changes there then I can pull changes and merge them with mine. The question is where would I clone this too?
Workbench directory?

**Comment by rtablada** [comment]
I would suggest using a second database connection if that would work for you. That let's you use a different database, or whatever.

**Comment by newtonianb** [comment]
Found a way to simply specify in composer.json your own version of the repo that it will use.
