### ISSUE TITLE
recompile less and coffee

### ISSUE THREAD

**Issue by newtonianb** [wardrobecms/core-archived#59]
Is there a built in command to do the recompilation of these two assets?
If I made changes what's the best way to recompile this?

**Comment by ericlbarnes** [comment]
Yes a built in way. I thought I had this in the readme but seems to be missing now :frowning: 

Here are the basic steps: 
1. Install NPM -> http://nodejs.org/
2. Install Grunt -> http://gruntjs.com/getting-started
3. (optional) Install Bower -> http://bower.io/

Then cd to the `core` directory and run `npm install`. After that finishes run `grunt` and everything will be recompiled.

**Comment by newtonianb** [comment]
very cool that worked thank you!

**Comment by newtonianb** [comment]
Actually I think there's a problem with the recompilation of the coffee... the less is working fine but after I recompiled / republish using grunt I get these errors

`Uncaught ReferenceError: Backbone is not defined`
`Uncaught ReferenceError: Wardrobe is not defined`

I compared the compiled structure.js with the original that worked and it's clearly different. The one compiled with grunt is missing these sections

start of first missing section
`* @preserve HTML5 Shiv v3.6.2 | @afarkas @jdalton @jon_neal @rem | MIT/GPL2 Licensed`
start of second missing section
`* JavaScript MD5 1.0.1`
start of third missing section

``` ;(function(){
/**
 * Require the given path.
 *
 * @param {String} path
 * @return {Object} exports
 * @api public
```

start of fourth missing section
`# More info at [www.dropzonejs.com](http://www.dropzonejs.com)`

**Comment by newtonianb** [comment]
it's because i had to not only do `npm install` but also `bower install`

**html5shiv issue**
the grunt file refers to `'assets/vendor/components/html5shiv/src/html5shiv.js'`
but with the latest bower install it gets html5shiv version 3.7.0 and the new path is `'assets/vendor/components/html5shiv/dist/html5shiv.js'`

**selectize issue**
the grunt file refers to `'assets/vendor/components/selectize/selectize.js'`
but with the latest bower install it gets html5shiv version 0.7.7 and the new path is `'assets/vendor/components/selectize/dist/js/standalone/selectize.js'`

I think we need to hardcode the versions in bower, right now they are all on latest

**Comment by ericlbarnes** [comment]
Ahh didn't realize this. Yeah I guess requiring a hard version would be best. 

Seems like there should be an automated way of knowing the paths through bower. 

—
Eric Barnes
