### ISSUE TITLE
Command "wardrobe:config" is not defined -- Typo

### ISSUE THREAD

**Issue by Tickthokk** [wardrobecms/core-archived#62]
Following the readme, I tried to run config.

![image](https://f.cloud.github.com/assets/128565/1289089/afc1417c-301b-11e3-9b3e-dbbb5cc61d56.png)

So then I run `warcrobe:cofig`:

![image](https://f.cloud.github.com/assets/128565/1289098/cae0f7f4-301b-11e3-887a-54c1cd3864fb.png)

And it works.  Just a command typo I'm sure.

**Comment by ericlbarnes** [comment]
Fixed in dev-master. See #61

**Comment by Tickthokk** [comment]
Ah, thanks!
