### ISSUE TITLE
Pagination bug while searching

### ISSUE THREAD

**Issue by mpmont** [wardrobecms/core-archived#65]
When paginating search results the query string for the search should be kept in the url.

example:

http://blog.marcomonteiro.net/archive?q=branching

when you hit the second page link you lost the search term and as a result you get all the articles on the archive.

**Comment by mpmont** [comment]
This seems to be almost working. Check this link here: http://blog.marcomonteiro.net/archive?page=2&q=sublime everything works fine from page one to page two. However the rest of the pages fail to work.

**Comment by ericlbarnes** [comment]
Can you look in your db and see how many results that search should actually be returning?  Maybe it's just returning a wrong total?

**Comment by mpmont** [comment]
The search is correct. So yeah, I guess that the total is wrong for the search. 

I've been testing and it's working on tags and all that. The search is the only one wrong.

**Comment by mpmont** [comment]
Awesome! =)
