### ISSUE TITLE
Laravel 4.1 Support

### ISSUE THREAD

**Issue by tpavlek** [wardrobecms/core-archived#76]
Currently wardrobe-core depends on 4.0.x. Will this be updated for Laravel 4.1?

**Comment by spamoom** [comment]
+1 on this

**Comment by carvefx** [comment]
+1 for laravel 4.1

**Comment by metalmatze** [comment]
I think wardrobe v2 will support at least 4.1.
Are there any missing features?

**Comment by MECU** [comment]
+1

**Comment by gregjrothwell** [comment]
+1

**Comment by Brancoady** [comment]
+1

**Comment by ericlbarnes** [comment]
Yes v2 is in the works and will be using the latest release of Laravel. 

V1 has some issues with the auth with Laravel 4.1. If anyone wants to send a pull request to fix that it would be appreciated.

**Comment by spamoom** [comment]
@ericbarnes Do you know if there's a github issue regarding the auth problem?

**Comment by ericlbarnes** [comment]
I'm not seeing one. I know @JesseObrien mentioned this to me in IRC and may have fixed it.

**Comment by jesseobrien** [comment]
I did indeed, I need to go back through and track what changes I made though. I'll try to get this up after work today.

**Comment by spamoom** [comment]
@JesseObrien Happy to pick up on the issue if I can - can you let me know where you got to?

**Comment by spamoom** [comment]
Turns out it was quite an easy fix - see #83
