### ISSUE TITLE
add configuration option for cache duration

### ISSUE THREAD

**Issue by intrip** [wardrobecms/core-archived#82]
Hello, i'm asking you if its possible to add a configuration option to set the duration of the cache used in getParsedContentAttribute()

**Comment by ericlbarnes** [comment]
I guess we could. Any particular reason since it should clear out when you edit a post. — Eric Barnes

**Comment by intrip** [comment]
Well, my bad then.I didn't realize it clears out when you edit a post (now i checked the code). Thanks anyways.
