### ISSUE TITLE
Running wardrobe:migrate fails

### ISSUE THREAD

**Issue by MECU** [wardrobecms/core-archived#85]
I'm on Laravel 4.1 using 1.0.\* Wardrobe/core

Installation works fine until I try:

```
php artisan wardrobe:migrate
```

and get this error:

```
 [Illuminate\Database\QueryException]
 SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`migration` varchar(255) not null, `batch` int not null) default character set utf8 collate utf8_unicode_ci)
```

In short, the database isn't getting initialized with the tables the Wardrobe needs. There is no 'users' table after migrating.

**Comment by ericlbarnes** [comment]
Can you look in your db and see if any tables are created? If so can you remove them and run the command again?

**Comment by MECU** [comment]
No tables were created. I did have tables in there from syntara. I deleted those (and removed syntara) and re-tried and still no tables were created.

**Comment by ericlbarnes** [comment]
I just tested this locally and didn't have issues. Here is what I did. Clone wardrobe/wardrobe, change composer to: 

```
"require": {
  "laravel/framework": "4.1.*",
  "wardrobe/core": "dev-master"
},
```

`composer install` and then follow the install steps. It created all the tables fine for me. 

Not really sure how to duplicate this. :frowning:

**Comment by MECU** [comment]
Would you please be a little more verbose in explaining:
Clone wardrobe/wardrobe
change composer: which one? in my app composer or wardrobe/wardrobe or wardrobe/core?
composer install where? My app or wardrobe/wardrobe or wardrobe/core?

What I did is require wardrobe/core in my app. I actually did it with the composer require wardrobe/core, version "master" (but I've also changed it to dev-master and it didn't change the install).

**Comment by MECU** [comment]
This was caused by my migration not being installed corrected. I was actually missing a line in my app.php config file that prevented being able to install migration. Thanks for taking a look.
