### ISSUE TITLE
4.1 not supporting

### ISSUE THREAD

**Issue by ghost** [wardrobecms/core-archived#87]
Not supporting 4.1 Laravel. Using:  `"wardrobe/core": "1.0.*"` in composer.json file. Same issue arises in package install. See screenshot:

![screen shot 2014-02-26 at 8 54 15 am](https://f.cloud.github.com/assets/3316306/2267291/f607202e-9eb2-11e3-8ec5-002142a61601.png)

**Comment by ericlbarnes** [comment]
what if you try `"wardrobe/core": "dev-master"` ?

**Comment by rtablada** [comment]
@ericbarnes is the change in required laravel version worthy of a 1.1.0 tag?

**Comment by rtablada** [comment]
Actually, I think that this could be done in a patch since we now require ~4 so it should not break any features from users of L4.0 that keep requiring 1.0.*

**Comment by ericlbarnes** [comment]
I think 1.1 is worthy. Would you mind helping set that up?

**Comment by rtablada** [comment]
Done
