### ISSUE TITLE
Run `php artisan wardrobe:migrate` with sqlite throws error

### ISSUE THREAD

**Issue by kenvunz** [wardrobecms/core-archived#95]
`
  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1 Cannot add a PRIMARY KEY column (SQL: alter table "tags" add column "id" integer not null primary key autoincrement)
`

I believe this is a limitation of SQLite, it doesn't allow adding a PRIMARY KEY column after table has been created

More details here `http://stackoverflow.com/questions/946011/sqlite-add-primary-key`

**Comment by Kukunin** [comment]
This bug affects me too. I ask author to increase priority of this bug. SQLite in-memory DB is the best solution for testing purposes - just create database in memory and run your tests. Due the migration error, it isn't possible.
I suggest to discuss about possible ways to solve this problem. I can see only one solution: merge migrations, which cause error. Not good solution, but I can't see another one
